from .mfcc_annotated_segments import mfcc_annotated_segments_data_pipeline_config
from .log_mel_spectrogram_annotated_segments import log_mel_spectrogram_annotated_segments_data_pipeline_config
from .mfcc_sliding_windows import mfcc_sliding_windows_data_pipeline_config
from .log_mel_spectrogram_sliding_windows import log_mel_spectrogram_sliding_windows_data_pipeline_config
from .downsampled_waveform_sliding_window import downsampled_waveform_sliding_window_data_pipeline_config


__all__ = [
    "log_mel_spectrogram_annotated_segments_data_pipeline_config",
    "mfcc_annotated_segments_data_pipeline_config",
    "log_mel_spectrogram_sliding_windows_data_pipeline_config",
    "mfcc_sliding_windows_data_pipeline_config",
    "downsampled_waveform_sliding_window_data_pipeline_config",
]
